apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deploy
  namespace: icgroup
  labels:
    app: pgadmin
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: "dpage/pgadmin4"
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: user@domain.com #je laisse la valuer par defaut
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: pgadmin-passwrd

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          volumeMounts:
            - name: pgadmin-volume
              mountPath: /var/lib/pgadmin # the working directory in which pgAdmin stores session data
            - name: pgadmin-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
            - name: pgadmin-pass
              mountPath: /pgpass # /pgpass
              subPath: pgpass

      volumes:
        - name: pgadmin-config
          configMap:
            name: pgadmin-config
        - name: pgadmin-pass
          configMap:
            name: pgadmin-config
            defaultMode: 0600
        - name: pgadmin-volume
          persistentVolumeClaim:
            claimName: pgadmin-pvc