apiVersion: v1
kind: ConfigMap
metadata:
 name: pgadmin-config
 namespace: icgroup
 labels:
    app: pgadmin
    env: prod
data:
 pgpass: db-service:5432:postgres:odoo:odoo
 servers.json: |
  {
    "Servers": {
      "1": {
        "Name": "pg",
        "Group": "Servers",
        "Port": 5432,
        "Username": "odoo",
        "Host": "db-service",
        "PassFile": "/pgpass",
        "SSLMode": "prefer",
        "MaintenanceDB": "postgres"
      }
    }
  }
 

 #"PassFile": "/pgpass", 
# db-service.icgroup.svc.cluster.local:5432:postgres:odoo:
# A ConfigMap is an API object used to store non-confidential data in key-value pairs.
# Pods can consume ConfigMaps as environment variables, command-line arguments
#db-service.icgroup.svc.cluster.local:5432:postgres:user_db:????
# or as configuration files in a volume.

