apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deploy 
  namespace: icgroup
  labels:
    app: odoo
    env: prod 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
      
    spec:
      containers:
      - name: odoo 
        image: odoo:13
        env:
          - name: HOST
            value: db-service
          - name: PASSWORD
            value: odoo
          - name: USER
            value: odoo 
        ports:
          - name: http
            containerPort: 8069