apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: icgroup
  labels:
    app: pgadmin
    env: prod
type: Opaque
data:
  pgadmin-passwrd: cGFzc3dvcmQtcGdhZG1pbg== #password in base 64 (password-pgadmin)
