apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: icgroup
  labels:
    app: db_odoo
    env: prod
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 200Mi
  accessModes:
    - ReadWriteOnce