apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: icgroup
  labels:
    app: db_odoo
    env: prod
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data-pv