apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: icgroup
  labels:
    app: db_odoo
    env: prod

spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: db_odoo