apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  namespace: icgroup
  labels:
    app: odoo-server
    env: prod
spec:
  type: NodePort
  ports:
    - port: 8069
      protocol: TCP
      targetPort: 8069
      nodePort: 32020
  selector:
    app: odoo